update
[skip ci]

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -28,10 +28,17 @@ jobs:
           git remote add upstream https://github.com/CodenameCrew/CodenameEngine.git
           git fetch upstream main
 
-      - name: Merge upstream into edge
+      - name: Merge upstream into main
         run: |
           git checkout main
-          git merge upstream/main -X ours --no-edit
+          
+          if ! git merge upstream/main -X ours --no-edit; then
+            echo "Merge failed. Checking for modify/delete conflicts..."
+            
+            git status --porcelain | grep '^DU ' | cut -c 4- | tr '\n' '\0' | xargs -0 -r git rm
+            
+            git commit --allow-empty -m "Auto-merged upstream/main and resolved deleted files"
+          fi
 
       - name: Push updated branch
         run: |
